import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :collaborlist, CollaborlistWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  url: [host: "127.0.0.1", port: 80]

# Do not print debug messages in production
config :logger, level: :info

config :collaborlist, :http_processor, GoogleCerts.HTTPProcessor.HTTPoisonProcessor

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :collaborlist, CollaborlistWeb.Endpoint,
#       ...,
#       url: [host: "example.com", port: 443],
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :collaborlist, CollaborlistWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# config :collaborlist, CollaborlistWeb.Endpoint,
#   # Possibly not needed, but doesn't hurt
#   http: [port: {:system, "PORT"}],
#   url: [host: System.get_env("APP_NAME") <> ".tlietz.com", port: 443],
#   secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE"),
#   server: true,
#   check_origin: ["https://" <> System.get_env("APP_NAME") <> ".tlietz.com"]
config :collaborlist, CollaborlistWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE")

config :collaborlist, Collaborlist.Repo,
  start_apps_before_migration: [:ssl],
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  ssl: true,
  pool_size: 10
